export const MODEL_CATALOG = [
  {
    name: 'llama3.2',
    label: 'Llama 3.2 3B',
    sizeHint: '~2 GB',
    description: "Meta's compact model. Fast for everyday Q&A and chat.",
    tag: 'chat' as const,
  },
  {
    name: 'llama3.2:1b',
    label: 'Llama 3.2 1B',
    sizeHint: '~1.3 GB',
    description: 'Smallest Llama. Very fast on low-memory machines.',
    tag: 'chat' as const,
  },
  {
    name: 'llama3.1',
    label: 'Llama 3.1 8B',
    sizeHint: '~4.9 GB',
    description: 'Balanced quality and speed. Great for long answers.',
    tag: 'chat' as const,
  },
  {
    name: 'mistral',
    label: 'Mistral 7B',
    sizeHint: '~4.1 GB',
    description: 'Strong reasoning and code. Popular general-purpose model.',
    tag: 'chat' as const,
  },
  {
    name: 'phi3.5',
    label: 'Phi 3.5 Mini',
    sizeHint: '~2.2 GB',
    description: "Microsoft's tiny but capable instruction model.",
    tag: 'chat' as const,
  },
  {
    name: 'qwen2.5:3b',
    label: 'Qwen 2.5 3B',
    sizeHint: '~1.9 GB',
    description: "Alibaba's multilingual and code-capable model.",
    tag: 'chat' as const,
  },
  {
    name: 'gemma2:2b',
    label: 'Gemma 2 2B',
    sizeHint: '~1.6 GB',
    description: "Google's efficient small model.",
    tag: 'chat' as const,
  },
  {
    name: 'nomic-embed-text',
    label: 'Nomic Embed Text',
    sizeHint: '~274 MB',
    description: 'Fast, high-quality text embeddings for semantic search.',
    tag: 'embed' as const,
  },
  {
    name: 'mxbai-embed-large',
    label: 'MXBai Embed Large',
    sizeHint: '~670 MB',
    description: 'Higher-accuracy embeddings. Slower but more precise.',
    tag: 'embed' as const,
  },
] as const;
